// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3pBcmvKmX9iKzX3r3QhqekST0opjOVOc',
    appId: '1:573479670734:web:56999ff666fba409be919f',
    messagingSenderId: '573479670734',
    projectId: 'majorproject-73a4f',
    authDomain: 'majorproject-73a4f.firebaseapp.com',
    storageBucket: 'majorproject-73a4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_VHZLAtZaY1d0qjB-0HxfX3yLrauMMY',
    appId: '1:573479670734:android:6e6cc25a48e8a9fdbe919f',
    messagingSenderId: '573479670734',
    projectId: 'majorproject-73a4f',
    storageBucket: 'majorproject-73a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXTSFFL1gDKHAncz9w9q5WetTm5cqcdQ',
    appId: '1:573479670734:ios:a4d95da357487af8be919f',
    messagingSenderId: '573479670734',
    projectId: 'majorproject-73a4f',
    storageBucket: 'majorproject-73a4f.appspot.com',
    iosBundleId: 'com.example.majorProject',
  );

}